language: python

python:
  - "3.8"

compiler:
  - clang

install:
  - "pip install --upgrade pip"
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
  - "python -m nltk.downloader punkt"
  - "python -m nltk.downloader averaged_perceptron_tagger"
  - "pip install --install-option=""--no-cython-compile"" cython"
  - "./upgrade_pystruct"

script:
  - "py.test"

services:
  - redis-server

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false