language: python

python:
  - "2.7"

install:
  - "pip install --upgrade pip"
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
  - "python -m nltk.downloader punkt"
  - "python -m nltk.downloader averaged_perceptron_tagger"

script:
  - "py.test"

services:
  - redis-server

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false