#!/usr/bin/env bash

mkdir pystruct
cd pystruct
pip download pystruct==0.3.2
git clone https://github.com/pystruct/pystruct
tar xzf pystruct-0.3.2.tar.gz
mv pystruct-0.3.2/src/utils.c pystruct-0.3.2/src/utils.save
cp pystruct/src/utils.pyx pystruct-0.3.2/src/
cython pystruct-0.3.2/src/utils.pyx
sed -i '' 's/tstate->exc_type/tstate->exc_state.exc_type/' pystruct-0.3.2/src/utils.c
sed -i '' 's/tstate->exc_value/tstate->exc_state.exc_value/' pystruct-0.3.2/src/utils.c
sed -i '' 's/tstate->exc_traceback/tstate->exc_state.exc_traceback/' pystruct-0.3.2/src/utils.c
sed -i '' 's/from sklearn.externals.joblib import Parallel, delayed/from joblib import Parallel, delayed/g' pystruct-0.3.2/pystruct/utils/*.py
sed -i '' 's/from sklearn.externals.joblib import Parallel, delayed/from joblib import Parallel, delayed/g' pystruct-0.3.2/pystruct/learners/*.py
sed -i '' 's/from sklearn.externals.joblib import Parallel, delayed, cpu_count/from joblib import Parallel, delayed, cpu_count/g' pystruct-0.3.2/pystruct/learners/*.py
cd pystruct-0.3.2 && python ./setup.py install
cd .. && cp -rf pystruct-0.3.2 ../python/lib/python3.8/site-packages/pystruct
cd ..
rm -rf pystruct


