name: GitHub Actions CI 

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        python -m nltk.downloader punkt
        python -m nltk.downloader averaged_perceptron_tagger

    - name: Test with pytest
      run: |
        py.test
    - run: coveralls
