name: GitHub Actions CI 

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        python -m nltk.downloader punkt
        python -m nltk.downloader averaged_perceptron_tagger

    - name: Upgrade pystruct
      run: |
        ./upgrade_pystruct

    - name: Test with pytest
      run: |
        py.test

    - name: Upload coverage data to coveralls.io
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
